In [2]:
print("Hello World")

Hello World


In [1]:
import pandas as pd

In [2]:
print("Sarvesh Satish Pathak")

Sarvesh Satish Pathak


In [3]:
list = ["Sarvesh","Kedar","Gaurav"]

In [4]:
print(list)

['Sarvesh', 'Kedar', 'Gaurav']


In [5]:
print(list[0])

Sarvesh


In [6]:
print(list[0:1])

['Sarvesh']


In [7]:
import pandas as pd

In [8]:
data = pd.read_csv("banknotes.csv")

In [9]:
print(data)

      Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]


In [10]:
data.shape

(1372, 5)

In [11]:
data.columns

Index(['Variance', 'Skewness', 'Curtosis', 'Entropy', 'Class'], dtype='object')

In [12]:
X = data.drop('Class',axis=1) #column vise operation is done.

In [13]:
X.head()

Variance  Skewness  Curtosis  Entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [14]:
y = data['Class']

In [15]:
X.isnull().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
dtype: int64

In [16]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: Class, Length: 1372, dtype: int64

In [17]:
set(y) #Shows the unique values.

{0, 1}

In [18]:
import numpy as np #another method to find the unique values.

In [19]:
np.unique(y)

array([0, 1])

In [20]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 0)

In [23]:
len(X_train)

1029

In [24]:
len(X_test)

343

In [25]:
X_train.head()

Variance  Skewness  Curtosis   Entropy
662     2.9736    8.7944   -3.6359 -1.375400
512     2.6648   10.7540   -3.3994 -4.168500
1193   -3.7573   -8.2916   10.3032  0.380590
682     3.7321   -3.8840    3.3577 -0.006049
1313   -1.5078   -7.3191    7.8981  1.228900

In [26]:
y_train.head()

662     0
512     0
1193    1
682     0
1313    1
Name: Class, dtype: int64

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
classifier = DecisionTreeClassifier()

In [29]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [30]:
y_pred = classifier.predict(X_test)

In [31]:
y_pred

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,

In [32]:
#For every prediction confusion matrix is important

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test,y_pred)

array([[194,   1],
       [  3, 145]])

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(y_test, y_pred) *100 #Checking accuracy for the dataset

98.83381924198251

In [37]:
from sklearn.metrics import classification_report

In [38]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       195
           1       0.99      0.98      0.99       148

    accuracy                           0.99       343
   macro avg       0.99      0.99      0.99       343
weighted avg       0.99      0.99      0.99       343



In [39]:
from sklearn.externals.six import StringIO

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [48]:
from sklearn.externals.six import StringIO #Visual representation 
#The tree will be saved in the home directory

In [41]:
from IPython.display import Image

In [42]:
from sklearn.tree import export_graphviz

In [43]:
import pydotplus

In [44]:
dot_data = StringIO()

In [45]:
export_graphviz(classifier, out_file=dot_data,filled=True,rounded=True,special_characters=True)

In [46]:
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

In [47]:
graph.write_png('tree.png')

True